# Generated by Django 5.0.2 on 2025-04-17 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='feedback',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='date_answered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='test',
            name='difficulty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='answer',
            field=models.CharField(max_length=1),
        ),
    ]
